  on: push
name: CI
jobs:
  build:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.0.0
      - name: Load repository
        uses: actions/checkout@master
      - name: Run tests
        timeout-minutes: 30
        run: |
          npm install
          npm run test:cov
      - name: Fix code coverage paths
        working-directory: ./coverage
        run: sed -i 's/\/home\/runner\/work\/my-nest-project\/my-nest-project\//\/github\/workspace\//g' lcov.info
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
